### ISSUE TITLE
RGI10 (North Asia) - Kamchatka 

### ISSUE THREAD

**Issue by idbarr** [GLIMS-RGI/rgi7_scripts#42]
In very far NE Siberia (i.e. on the Chukchi Peninsula, bordering the Bering Strait), because mapped glaciers lie East of 180° longitude they are often 'lost' or incorrectly projected, depending which platform/format is used for viewing.

**Comment by fmaussion** [comment]
@idbarr thanks for the feedback! I wouldn't be surprised ;-) 

Can you point us towards specific problems, screenshots? Are the glaciers available in the GLIMS viewer? https://www.glims.org/maps/glims

**Comment by idbarr** [comment]
They appear ok in the GLIMS viewer - so perhaps no an issue.

**Comment by fmaussion** [comment]
Here is the current RGI7 alpha file: https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l3_rgi7a_tar/RGI10.tar.gz 

We would be very grateful if you could have an expert look at it!

**Comment by Akiko-Sakai** [comment]
As for Kamchatka, I found an old inventory in Bulletin of Glacier Research.
https://web.seppyo.org/bgr/pdf/15/BGR15P19.PDF     (in Fig.1)
In this inventory there are glaciers in the southern end of this Kamchatka Peninsula.
I wonder those glaciers have disappeared because of the recent warming. But, in the Landsat8 taken in 1st Sep, 2016 (Path99 Row24), (this scene has the least snow cover in recent scenes)I could find at least two glaciers as shown in attached file. Those might be very small and insignificant.
Anyway, I report on the alpha version of RGI10 .

Looking at RGI10 reminds me that it is a very hard task to show that there are no glaciers...

![Kamchatka_south](https://user-images.githubusercontent.com/98805726/151939671-b98fccf6-1ed6-46b5-ba18-69236f59e7eb.JPG)
![Landsat8_20160901](https://user-images.githubusercontent.com/98805726/151939689-026279a8-a41e-4bac-8ef8-639d21342a85.JPG)

**Comment by idbarr** [comment]
RE the glaciers in far southern Kamchatka:
These were included in the shapefiles I shared last year (see fig below) but have subsequently dissapeared from the datset.
I'm not sure if this is a mistake or a decision (given that the sahpefiles for Kamchatka have been modified/merged significanlty since uploading)   

![Picture1](https://user-images.githubusercontent.com/98599276/151954371-d14d83e7-f0cd-4715-b684-5566a1f0764d.jpg)

**Comment by fmaussion** [comment]
Thank you both for these comments! Very useful. I know which entities you are talking about, and I noticed that they were missing while creating the RGI. 

For some reason, Frank decided not to have them in his revision of the region ([submission id 743](https://github.com/GLIMS-RGI/rgi7_scripts/wiki/RGI10-(North-Asia)) - this is probably an oversight, I will ask him what to do about it.

**Comment by fmaussion** [comment]
Note that they are in GLIMS, so adding them to RGI is no big issue:

![image](https://user-images.githubusercontent.com/10050469/151956341-c7e5332b-39a6-4ac9-8c0e-91b36e23df82.png)

**Comment by fmaussion** [comment]
Answer from Frank (who has yet to be convinced by github :wink:):

---

Thank you for forwarding the feedback! As a first reaction I would say they have been forgotten in my version and should be included. I will quickly check if I can find some satellite images from around 2000 to see if the existing outlines are valid and can be used as is.

Best, Frank

**Comment by fmaussion** [comment]
I've asked Frank again - if no response I'll go ahead and include these outlines from GLIMS

**Comment by fmaussion** [comment]
Done! These glaciers are back in RGI7 - thanks all for the review
